---
title: "Curating a Data Science Resource"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Individual Final Project

### Overview

This assignment involves identifying and describing a data science resource as a part of a class resource throughout the semester.

### Details

While you work on your final project, you are very likely going to be doing some independent research. This independent research may lead you to resources, R packages, or even individuals who you found very helpful. This assignment is an opportunity for you, individually, and us, as a class, to share these resources with each other, students in future classes, and anyone interested!

### Process and Timeline and Due Dates

- By 5/5, add your resource to the R Markdown document in the repository for this website:
  

### Other resources

Available data sets:

- Your own!
- Education data package: https://github.com/UrbanInstitute/education-data-package-r
- Data from Twitter: https://developer.twitter.com/en/solutions/academic-research
- Data from Facebook: https://help.crowdtangle.com/en/articles/4302208-crowdtangle-for-academics-and-researchers
- Other ideas for data sets?

### How to submit

- Please submit a Google Docs link for this assignment on Canvas. Also, please post that link to the #data-ethics-statement channel on Slack (you may have to browse and then add the channel to access it). Be sure that the sharing settings are such that anyone with the link can comment on the document. 

